# version: '3.9'
# services:
#   db:
#     image: postgres:latest
#     restart: always
#     env_file:
#       - ./database/.env
#     ports:
#       - "27019:27019"
#     volumes:
#       - data:/var/lib/postgresql/data
# volumes:
#   data:

version: '3.9'
services:
  db:
    container_name: newdb
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 27021:27021
    env_file:
      - ./database/.env
volumes:
  data:
